"""added suport for replies

Revision ID: bff73bb2040c
Revises: 2f0b4565a990
Create Date: 2025-12-16 21:40:25.692764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff73bb2040c'
down_revision = '2f0b4565a990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        # Add 'direction' column as nullable first
        batch_op.add_column(sa.Column('direction', sa.String(length=20), nullable=True))
        # Populate existing rows with a default value for 'direction'
        batch_op.execute("UPDATE emails SET direction = 'SENT'")
        # Alter 'direction' column to be NOT NULL
        batch_op.alter_column('direction', existing_type=sa.String(length=20), nullable=False)

        # Add 'sender_email' column as nullable first
        batch_op.add_column(sa.Column('sender_email', sa.String(length=120), nullable=True))
        # Populate existing rows with a default value for 'sender_email' (assuming existing emails were sent by the recipient)
        batch_op.execute("UPDATE emails SET sender_email = recipient_email")
        # Alter 'sender_email' column to be NOT NULL
        batch_op.alter_column('sender_email', existing_type=sa.String(length=120), nullable=False)

        # Add 'brevo_message_id' column (already nullable)
        batch_op.add_column(sa.Column('brevo_message_id', sa.String(length=255), nullable=True))
        
        batch_op.create_index(batch_op.f('ix_emails_brevo_message_id'), ['brevo_message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_emails_direction'), ['direction'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_direction'))
        batch_op.drop_index(batch_op.f('ix_emails_brevo_message_id'))
        batch_op.drop_column('brevo_message_id')
        batch_op.drop_column('sender_email')
        batch_op.drop_column('direction')

    # ### end Alembic commands ###
