"""added suport for replies

Revision ID: bff73bb2040c
Revises: 2f0b4565a990
Create Date: 2025-12-16 21:40:25.692764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff73bb2040c'
down_revision = '2f0b4565a990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.String(length=20), nullable=False, server_default='OUTBOUND'))
        batch_op.add_column(sa.Column('sender_email', sa.String(length=120), nullable=False, server_default='default@sender.com'))
        
        # Add 'brevo_message_id' column (already nullable)
        batch_op.add_column(sa.Column('brevo_message_id', sa.String(length=255), nullable=True))
        
        batch_op.create_index(batch_op.f('ix_emails_brevo_message_id'), ['brevo_message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_emails_direction'), ['direction'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_direction'))
        batch_op.drop_index(batch_op.f('ix_emails_brevo_message_id'))
        batch_op.drop_column('brevo_message_id')
        batch_op.drop_column('sender_email')
        batch_op.drop_column('direction')

    # ### end Alembic commands ###
